apiVersion: apps/v1
kind: Deployment
metadata:
  name: dias-especiales-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dias-especiales-service
  template:
    metadata:
      labels:
        app: dias-especiales-service
    spec:
      containers:
        - name: dias-especiales-service
          image: isaaccumbia/dias-especiales-service:latest
          ports:
            - containerPort: 8080
          env:
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: dias-especiales-service-secret
                  key: db-username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: dias-especiales-service-secret
                  key: db-password
---
apiVersion: v1
kind: Service
metadata:
  name: dias-especiales-service
spec:
  selector:
    app: dias-especiales-service
  ports:
    - port: 8080
      targetPort: 8080
