apiVersion: apps/v1
kind: Deployment
metadata:
  name: reservas-comprobantes-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reservas-comprobantes-db
  template:
    metadata:
      labels:
        app: reservas-comprobantes-db
    spec:
      containers:
        - name: mysql
          image: mysql:8.0
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: reservas-comprobantes-service-secret
                  key: db-password
            - name: MYSQL_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: reservas-comprobantes-service-config
                  key: MYSQL_DATABASE
---
apiVersion: v1
kind: Service
metadata:
  name: reservas-comprobantes-db
spec:
  selector:
    app: reservas-comprobantes-db
  ports:
    - port: 3306
      targetPort: 3306
