apiVersion: apps/v1
kind: Deployment
metadata:
  name: plan-service-deployment
  labels:
    app: plan-service-deployment
spec:
  selector:
    matchLabels:
      app: plan-service-deployment
  replicas: 1
  template:
    metadata:
      labels:
        app: plan-service-deployment
    spec:
      containers:
        - name: plan-service
          image: isaaccumbia/plan-service:latest
          ports:
            - containerPort: 8090
          env:
            - name: SERVER_PORT
              value: "0"

            - name: DB_HOST
              value: "plan-db"
            - name: DB_PORT
              value: 3306
            
            - name: DB_DBNAME
              valueFrom:
                configMapKeyRef:
                  name: plan-service-config
                  key: MYSQL_DATABASE
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: plan-service-secret
                  key: db-username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: plan-service-secret
                  key: db-password