CREATE DATABASE IF NOT EXISTS cliente_db;
CREATE DATABASE IF NOT EXISTS plan_db;
CREATE DATABASE IF NOT EXISTS descuento_grupo_db;
CREATE DATABASE IF NOT EXISTS dias_especiales_db;
CREATE DATABASE IF NOT EXISTS rack_semanal_db;
CREATE DATABASE IF NOT EXISTS reserva_db;
CREATE DATABASE IF NOT EXISTS reportes_db;
