server:
  port: 8081
spring:
  cloud:
    config:
      server:
        git:
          default-label: main
          uri: https://github.com/IsaacEspinoza91/Tingeso-Entrega-2
          search-paths: config-data
  application:
    name: config-service