server:
  port: 8081
spring:
  cloud:
    config:
      server:
        git:
          default-label: Desarrollo-ejec
          uri: https://github.com/IsaacEspinoza91/Tingeso-Entrega-2
          search-paths: Backend-KartingRM/config-data
          clone-on-start: true
  application:
    name: config-service